### ISSUE TITLE
HDMI

### ISSUE THREAD

**Issue by uiltonlopes** [ppjjhh/Hackintosh-Dell-Inspiron-7580#1]
Tenho o mesmo note, vc conseguiu deixar o HDMI 100%??? o meu só falta isso.

**Comment by ppjjhh** [comment]
i am sorry i don't understand what you said.

**Comment by wq133** [comment]
He said: I have the same instructions, you managed to keep 100% of THE HDMI? Mine just lacks it.

**Comment by ppjjhh** [comment]
I have not tried an external monitor, so i don't know how to fix this problem. Sorry.
