### ISSUE TITLE
Sleep After Boot

### ISSUE THREAD

**Issue by OswinWu** [ppjjhh/Hackintosh-Dell-Inspiron-7580#2]
During booting, the backlight of the screen is gone. And after that, the computer will automatically fall sleep. Is that just me or?

**Comment by ppjjhh** [comment]
Have you unlock CFG-lock? I have not encountered this problem. Don’t plug in headphones when turning on.

**Comment by OswinWu** [comment]
Oh, I haven't, I will try now, thank U

**Comment by OswinWu** [comment]
I've just unlocked cfg-lock, but nothing changed.

**Comment by ppjjhh** [comment]
Don’t plug in headphones or other device when booting.

**Comment by OswinWu** [comment]
I remove the mouse receiver and USB, then worked!Thank U again!

**Comment by ppjjhh** [comment]
i suggest when you want to debug you should turn on the opencore debug mode, which is add a value "-v" in boot-args.
