### ISSUE TITLE
进入安装界面后重启  bios只关闭安全启动

### ISSUE THREAD

**Issue by notepaper** [ppjjhh/Hackintosh-Dell-Inspiron-7580#3]
进入安装界面后重启  bios只关闭安全启动

**Comment by ppjjhh** [comment]
不太懂，可以描述清楚一点吗？

**Comment by dm5n** [comment]
感谢您提供本指南和EFI文件夹。 我可以在单独的NVMe驱动器上安装macOS吗？

**Comment by ppjjhh** [comment]
肯定可以啊，我就是单独一个nvme盘装苹果，用得挺爽的，建议你用我最新的release，记得备份数据，数据最好不要放在黑苹果nvme系统盘



---Original---

**Comment by dm5n** [comment]
太棒了。非常感谢。我计划将Windows 10保留在内部ssd上，并为双启动系统添加用于hackintosh的NVMe驱动器。那是你做的吗？

**Comment by ppjjhh** [comment]
acpi部分不是我做的，用dell同型号电脑东拼西凑搞出来的，其他的，参考&nbsp;https://dortania.github.io/OpenCore-Install-Guide/



---Original---

**Comment by dm5n** [comment]
优秀的。我最近使用OpenCore和其他人的指南将Dell 9020台式机转换为hackintosh。您的EFI可能会有很大的帮助。

**Comment by ppjjhh** [comment]
It's my pleasure to help you.



---Original---

**Comment by dm5n** [comment]
非常感谢。我要订购三星ssd，因为笔记本电脑中已经有一个Toshiba NVMe驱动器。然后尝试使用双引导系统。您必须更换wifi卡吗？什么？

**Comment by ppjjhh** [comment]
必须更换无线网卡，三星硬盘有些不兼容，建议去https://www.tonymacx86.com/查看硬件是否兼容



---Original---

**Comment by dm5n** [comment]
好的。非常感谢您的慷慨帮助。

**Comment by dm5n** [comment]
你好 我能问你几个问题吗？

我已经开始在Dell 7580上安装macOS并按照您的指南进行操作。

您的EFI文件夹不包含命令行管理程序文件夹和bootx64.efi文件？

谢谢

**Comment by ppjjhh** [comment]
user the release.     https://github.com/ppjjhh/Hackintosh-Dell-Inspiron-7580/releases/download/0.6.2/EFI.zip

**Comment by ppjjhh** [comment]
https://github.com/ppjjhh/Hackintosh-Dell-Inspiron-7580/releases/download/0.6.2/EFI.zip


use the release&nbsp;



---Original---

**Comment by dm5n** [comment]
是的，我下载了。

但是EFI文件夹中没有“ Shell”文件夹
[image: image.png]

**Comment by ppjjhh** [comment]
I've just uploaded 「shell」zip. Check the release again



---Original---

**Comment by dm5n** [comment]
我的错。

现在，我已经看到您已经将其上传到那里了。

非常感谢 ：）

会告诉你这件事的进展的。

**Comment by dm5n** [comment]
太棒了 如您所描述的那样，它起作用并更改了CFG。

下一个问题是计算机无法从USB启动。 说“找不到启动设备”。



> 我的错。
>
> 现在，我已经看到您已经将其上传到那里了。
>
> 非常感谢 ：）
>
> 会告诉你这件事的进展的。
>
> On Fri, Oct 30, 2020 at 5:50 PM A freshman <notifications@github.com>
> wrote:
>
>> I've just uploaded 「shell」zip. Check the release again
>>
>>
>>
>> ---Original---
>> From: "dm5n"<notifications@github.com&gt;
>> Sent at: 2020年10月30日(Fri) PM2:41
>> To: "ppjjhh/Hackintosh-Dell-Inspiron-7580"<
>> Hackintosh-Dell-Inspiron-7580@noreply.github.com&gt;;
>> Cc: "Comment"<comment@noreply.github.com&gt;;"A freshman"<
>> ppjjhh@foxmail.com&gt;;
>> Subject: Re: [ppjjhh/Hackintosh-Dell-Inspiron-7580] 进入安装界面后重启 bios只关闭安全启动
>> (#3)
>>
>>
>>
>>
>> 是的，我下载了。
>>
>> 但是EFI文件夹中没有“ Shell”文件夹
>> [image: image.png]
>>
>> On Fri, Oct 30, 2020 at 5:38 PM A freshman <notifications@github.com&gt;
>> wrote:
>>
>> &gt;
>> &gt;
>> https://github.com/ppjjhh/Hackintosh-Dell-Inspiron-7580/releases/download/0.6.2/EFI.zip
>> &gt;
>> &gt;
>> &gt; use the release&amp;nbsp;
>> &gt;
>> &gt;
>> &gt;
>> &gt; ---Original---
>> &gt; From: "dm5n"<notifications@github.com&amp;gt;
>> &gt; Sent at: 2020年10月30日(Fri) PM2:28
>> &gt; To: "ppjjhh/Hackintosh-Dell-Inspiron-7580"<
>> &gt; Hackintosh-Dell-Inspiron-7580@noreply.github.com&amp;gt;;
>> &gt; Cc: "Comment"<comment@noreply.github.com&amp;gt;;"A freshman"<
>> &gt; ppjjhh@foxmail.com&amp;gt;;
>> &gt; Subject: Re: [ppjjhh/Hackintosh-Dell-Inspiron-7580] 进入安装界面后重启
>> bios只关闭安全启动
>> &gt; (#3)
>> &gt;
>> &gt;
>> &gt;
>> &gt;
>> &gt; 你好 我能问你几个问题吗？
>> &gt;
>> &gt; 我已经开始在Dell 7580上安装macOS并按照您的指南进行操作。
>> &gt;
>> &gt; 您的EFI文件夹不包含命令行管理程序文件夹和bootx64.efi文件？
>> &gt;
>> &gt; 谢谢
>> &gt;
>> &gt; On Sun, Oct 18, 2020 at 6:50 PM Dihan Wijewickrama <

**Comment by ppjjhh** [comment]
sorry, this is a tough issue. I can't help&nbsp; you. you can find the answer at this website&nbsp; &nbsp; https://www.tonymacx86.com/



---Original---

**Comment by dm5n** [comment]
非常感谢您的帮助。

**Comment by dm5n** [comment]
我按照您的指南进行了工作，并进行了一些更改：

我为i7-8565 CPU使用MacBookPro 15,1 SMBIOS而不是15,2，
还从config.plist中删除了所有Broadcom条目，因为笔记本电脑仍具有Intel Wifi。 显然现在有一种方法可以使此工作正常运行
https://github.com/OpenIntelWireless/itlwm

然后我将Realtek kext更改为这一
https://github.com/Mieze/RTL8111_driver_for_OS_X/releases/tag/V2.3.0。

我还在https://opencore.slowgeek.com/的OpenCore config.plist检查器之后进行了一些更改。

再次感谢！


> 非常感谢您的帮助。
>
> On Fri, Oct 30, 2020 at 10:21 PM A freshman <notifications@github.com>
> wrote:
>
>> sorry, this is a tough issue. I can't help&nbsp; you. you can find the
>> answer at this website&nbsp; &nbsp; https://www.tonymacx86.com/
>>
>>
>>
>> ---Original---
>> From: "dm5n"<notifications@github.com&gt;
>> Sent at: 2020年10月30日(Fri) Evening6:25
>> To: "ppjjhh/Hackintosh-Dell-Inspiron-7580"<
>> Hackintosh-Dell-Inspiron-7580@noreply.github.com&gt;;
>> Cc: "Comment"<comment@noreply.github.com&gt;;"A freshman"<
>> ppjjhh@foxmail.com&gt;;
>> Subject: Re: [ppjjhh/Hackintosh-Dell-Inspiron-7580] 进入安装界面后重启 bios只关闭安全启动
>> (#3)
>>
>>
>>
>>
>> 太棒了 如您所描述的那样，它起作用并更改了CFG。
>>
>> 下一个问题是计算机无法从USB启动。 说“找不到启动设备”。
>>
>>
>>
>> &gt; 我的错。
>> &gt;
>> &gt; 现在，我已经看到您已经将其上传到那里了。
>> &gt;
>> &gt; 非常感谢 ：）
>> &gt;
>> &gt; 会告诉你这件事的进展的。
>> &gt;
>> &gt; On Fri, Oct 30, 2020 at 5:50 PM A freshman <notifications@github.com&gt;
>>
>> &gt; wrote:
>> &gt;
>> &gt;&gt; I've just uploaded 「shell」zip. Check the release again
>> &gt;&gt;
>> &gt;&gt;
>> &gt;&gt;
>> &gt;&gt; ---Original---
>> &gt;&gt; From: "dm5n"<notifications@github.com&amp;gt;
>> &gt;&gt; Sent at: 2020年10月30日(Fri) PM2:41
>> &gt;&gt; To: "ppjjhh/Hackintosh-Dell-Inspiron-7580"<
>> &gt;&gt; Hackintosh-Dell-Inspiron-7580@noreply.github.com&amp;gt;;
>> &gt;&gt; Cc: "Comment"<comment@noreply.github.com&amp;gt;;"A freshman"<
>> &gt;&gt; ppjjhh@foxmail.com&amp;gt;;
>> &gt;&gt; Subject: Re: [ppjjhh/Hackintosh-Dell-Inspiron-7580] 进入安装界面后重启
>> bios只关闭安全启动
>> &gt;&gt; (#3)
>> &gt;&gt;
>> &gt;&gt;
>> &gt;&gt;
>> &gt;&gt;
>> &gt;&gt; 是的，我下载了。
>> &gt;&gt;
>> &gt;&gt; 但是EFI文件夹中没有“ Shell”文件夹
>> &gt;&gt; [image: image.png]
>> &gt;&gt;
>> &gt;&gt; On Fri, Oct 30, 2020 at 5:38 PM A freshman <
>> notifications@github.com&amp;gt;
>> &gt;&gt; wrote:
>> &gt;&gt;
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt;
>> &gt;&gt;
>> https://github.com/ppjjhh/Hackintosh-Dell-Inspiron-7580/releases/download/0.6.2/EFI.zip
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt; use the release&amp;amp;nbsp;
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt; ---Original---
>> &gt;&gt; &amp;gt; From: "dm5n"<notifications@github.com&amp;amp;gt;
>> &gt;&gt; &amp;gt; Sent at: 2020年10月30日(Fri) PM2:28
>> &gt;&gt; &amp;gt; To: "ppjjhh/Hackintosh-Dell-Inspiron-7580"<
>> &gt;&gt; &amp;gt; Hackintosh-Dell-Inspiron-7580@noreply.github.com&amp;amp;gt;;
>>
>> &gt;&gt; &amp;gt; Cc: "Comment"<comment@noreply.github.com&amp;amp;gt;;"A
>> freshman"<
>> &gt;&gt; &amp;gt; ppjjhh@foxmail.com&amp;amp;gt;;
>> &gt;&gt; &amp;gt; Subject: Re: [ppjjhh/Hackintosh-Dell-Inspiron-7580]
>> 进入安装界面后重启
>> &gt;&gt; bios只关闭安全启动
>> &gt;&gt; &amp;gt; (#3)
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt; 你好 我能问你几个问题吗？
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt; 我已经开始在Dell 7580上安装macOS并按照您的指南进行操作。
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt; 您的EFI文件夹不包含命令行管理程序文件夹和bootx64.efi文件？
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt; 谢谢
>> &gt;&gt; &amp;gt;
>> &gt;&gt; &amp;gt; On Sun, Oct 18, 2020 at 6:50 PM Dihan Wijewickrama <

**Comment by dm5n** [comment]
另外，我在笔记本电脑中安装了一个1TB的SSD –因此，有Windows的原始NVMe和运行macOS的SSD。

**Comment by ppjjhh** [comment]
well done&nbsp;



---Original---

**Comment by ppjjhh** [comment]
my ssd is kioxia rd10, wifi adapter is broadcom&nbsp; 1820a

---Original---

**Comment by dm5n** [comment]
我可以再问一个问题吗？

您如何找到Intel图形的帧缓冲区设置？

难以使HDMI正常工作。 一直在这里遵循指南：https://www.reddit.com/r/hackintosh/comments/hu46xm/fix_hdmi_port_and_possfully_others_not_working_on/

**Comment by ppjjhh** [comment]
I haven't tried the HDMI, There is a [config&nbsp; file] , I think you can&nbsp; fix this issue through it.



---Original---

**Comment by dm5n** [comment]
Thankyou.

**Comment by ppjjhh** [comment]
https://www.tonymacx86.com/threads/dell-vostro-3480-i5-8265u-uhd-620.305636/&nbsp; &nbsp; &nbsp; &nbsp;<-&nbsp; Try this. I can't help you, because i don't have a monitor.&nbsp; &nbsp; PS:[con1] means hdmi. [con0] means type-c.&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by dm5n** [comment]
Hi, have you upgraded to Big Sur?

**Comment by ppjjhh** [comment]
Not yet. No rush.

---Original---

**Comment by dm5n** [comment]
👍
