### ISSUE TITLE
能否添加intel网卡驱动？

### ISSUE THREAD

**Issue by zb781834020** [ppjjhh/Hackintosh-Dell-Inspiron-7580#4]
非常感谢分享OC引导！

现在intel网卡可以由此项目贡献的驱动来使用了https://github.com/OpenIntelWireless/itlwm，不知能否添加到驱动中，谢谢！

**Comment by ppjjhh** [comment]
我不太清楚，你可以自己试试



---Original---
From: ***@***.***&gt;
Sent at: 2021年7月9日(Fri) Noon12:36
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ppjjhh/Hackintosh-Dell-Inspiron-7580] 能否添加intel网卡驱动？ (#4)




 
非常感谢分享OC引导！
 
现在intel网卡可以由此项目贡献的驱动来使用了https://github.com/OpenIntelWireless/itlwm，不知能否添加到驱动中，谢谢！
