### ISSUE TITLE
1820a 无法找到以太网

### ISSUE THREAD

**Issue by devinryu** [ppjjhh/Hackintosh-Dell-Inspiron-7580#5]
只有 PPPoE 和 6to4
![image](https://user-images.githubusercontent.com/42215787/125215376-ee6a4300-e2ed-11eb-8cba-f3e37f65d677.png)

**Comment by ppjjhh** [comment]
是在黑果小兵那里买的吗？我是他那买的，我的可以。https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html



---Original---
From: ***@***.***&gt;
Sent at: 2021年7月12日(Mon) AM8:49
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ppjjhh/Hackintosh-Dell-Inspiron-7580] 1820a 无法找到以太网 (#5)




 
只有 PPPoE 和 6to4

**Comment by devinryu** [comment]
应该不是硬件的问题，按照教程设置了一遍发现还是不行

**Comment by ppjjhh** [comment]
天线会不会接错了



---Original---
From: ***@***.***&gt;
Sent at: 2021年7月12日(Mon) AM9:38
To: ***@***.***&gt;;
Cc: "A ***@***.******@***.***&gt;;
Subject: Re: [ppjjhh/Hackintosh-Dell-Inspiron-7580] 1820a 无法找到以太网 (#5)




 
应该不是硬件的问题，按照教程设置了一遍发现还是不行

**Comment by ppjjhh** [comment]
或者清空一下kext缓存试试



---Original---
From: ***@***.***&gt;
Sent at: 2021年7月12日(Mon) AM9:38
To: ***@***.***&gt;;
Cc: "A ***@***.******@***.***&gt;;
Subject: Re: [ppjjhh/Hackintosh-Dell-Inspiron-7580] 1820a 无法找到以太网 (#5)




 
应该不是硬件的问题，按照教程设置了一遍发现还是不行

**Comment by ppjjhh** [comment]
重建缓存试试，一共需要三个kext，排列顺序不要错了，建议直接用我的releses试试。戴尔灵越7580.
